import React, {useEffect, useRef} from 'react';
import {
  AbsoluteFill,
  Easing,
  Img,
  Sequence,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';

type SubtitleSegment = {
  text: string;
  start: number;
  end: number;
};

const subtitleData: SubtitleSegment[] = [
  {text: 'If not me, then who. If not now, then when.', start: 0, end: 75},
  {text: 'I like using AI, and I believe many of you do too.', start: 75, end: 150},
  {text: 'This course is not just about using AI for fun.', start: 150, end: 225},
  {text: 'It is about learning how to use AI wisely, creatively, and responsibly.', start: 225, end: 300},

  {text: 'This is an experimental course.', start: 300, end: 390},
  {text: 'I will teach you how I use AI, and you will also teach me how you use AI.', start: 390, end: 510},
  {text: 'All assignments are expected to be completed in collaboration with AI.', start: 510, end: 630},

  {text: 'Class participation is important because this course depends on discussion, sharing, and experimentation with AI.', start: 630, end: 780},
  {text: 'You will also explore what kinds of images should not be generated by AI, and why.', start: 780, end: 900},
  {text: 'Then, we will use AI to conduct research, create a Gemini Gem, and generate slides for a presentation about different AI policies.', start: 900, end: 1080},
  {text: 'Lastly, you will learn how to use AI to create a web app and compile all your work into one webpage.', start: 1080, end: 1215},

  {text: "That's all for this course. If you don't take this course, then who?", start: 1215, end: 1320},
];


const useSpeechNarration = (activeText: string | null) => {
  const lastSpokenRef = useRef<string | null>(null);

  useEffect(() => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window) || !activeText) {
      return;
    }

    if (lastSpokenRef.current === activeText) {
      return;
    }

    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(activeText);
    utterance.lang = 'en-US';
    utterance.rate = 0.97;
    utterance.pitch = 1;
    window.speechSynthesis.speak(utterance);
    lastSpokenRef.current = activeText;

    return () => {
      window.speechSynthesis.cancel();
    };
  }, [activeText]);
};

const FloatingSymbols: React.FC = () => {
  const frame = useCurrentFrame();
  const symbols = ['∑', '∞', 'π', 'λ', '∫', '⊕', '√', 'Δ'];

  return (
    <>
      {symbols.map((symbol, i) => {
        const driftX = Math.sin((frame + i * 30) / 40) * 50;
        const driftY = Math.cos((frame + i * 25) / 45) * 35;
        const rotate = (frame * 0.25 + i * 30) % 360;

        return (
          <div
            key={symbol}
            style={{
              position: 'absolute',
              left: `${8 + i * 11}%`,
              top: `${14 + (i % 4) * 16}%`,
              transform: `translate(${driftX}px, ${driftY}px) rotate(${rotate}deg)`,
              color: 'rgba(162, 211, 255, 0.55)',
              fontSize: 34 + (i % 3) * 8,
              fontWeight: 500,
              textShadow: '0 0 16px rgba(102, 214, 255, 0.7)',
            }}
          >
            {symbol}
          </div>
        );
      })}
    </>
  );
};

const HUDOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const scanX = interpolate(frame % 180, [0, 179], [0, 1920]);

  return (
    <>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background:
            'radial-gradient(circle at 50% 50%, rgba(23,60,125,0.16), rgba(3,8,18,0.82)), linear-gradient(transparent 96%, rgba(151,235,255,0.08) 100%)',
        }}
      />
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: scanX,
          width: 2,
          height: '100%',
          background: 'linear-gradient(to bottom, transparent, rgba(120,247,255,0.8), transparent)',
          boxShadow: '0 0 20px rgba(120,247,255,0.8)',
          opacity: 0.5,
        }}
      />
    </>
  );
};

const Subtitle: React.FC = () => {
  const frame = useCurrentFrame();
  const active = subtitleData.find((s) => frame >= s.start && frame < s.end);
  if (!active) return null;

  const entrance = spring({
    frame: frame - active.start,
    fps: 30,
    config: {damping: 200, stiffness: 180},
  });

  return (
    <div
      style={{
        position: 'absolute',
        bottom: 84,
        left: '50%',
        transform: `translateX(-50%) scale(${interpolate(entrance, [0, 1], [0.92, 1], {
          extrapolateLeft: 'clamp',
          extrapolateRight: 'clamp',
        })})`,
        maxWidth: 1380,
        textAlign: 'center',
        color: '#ebf7ff',
        fontSize: 44,
        lineHeight: 1.28,
        fontFamily: 'SF Pro Display, Inter, Arial, sans-serif',
        fontWeight: 600,
        letterSpacing: 0.5,
        textShadow: '0 4px 26px rgba(0,0,0,0.65)',
        padding: '22px 34px',
        borderRadius: 24,
        backdropFilter: 'blur(10px)',
        background: 'linear-gradient(120deg, rgba(5,15,28,0.56), rgba(12,40,78,0.36))',
        border: '1px solid rgba(140,230,255,0.25)',
      }}
    >
      {active.text}
    </div>
  );
};

const SceneLayer: React.FC<{src: string; sceneFrame: number}> = ({src, sceneFrame}) => {
  const {width, height} = useVideoConfig();
  const zoom = interpolate(sceneFrame, [0, 330], [1.04, 1.12], {
    easing: Easing.bezier(0.25, 0.1, 0.25, 1),
    extrapolateRight: 'clamp',
  });

  const panX = Math.sin(sceneFrame / 90) * 20;
  const panY = Math.cos(sceneFrame / 120) * 16;

  return (
    <AbsoluteFill>
      <Img
        src={src}
        style={{
          width,
          height,
          objectFit: 'cover',
          transform: `scale(${zoom}) translate(${panX}px, ${panY}px)`,
          filter: 'brightness(0.62) saturate(1.15) contrast(1.1)',
        }}
      />
    </AbsoluteFill>
  );
};

const DataViz: React.FC = () => {
  const frame = useCurrentFrame();

  return (
    <svg width={1920} height={1080} style={{position: 'absolute', inset: 0}}>
      {new Array(7).fill(0).map((_, i) => {
        const yBase = 220 + i * 92;
        const progress = (frame * (1.4 + i * 0.05)) % 1920;
        return (
          <polyline
            key={i}
            points={`0 ${yBase} ${progress * 0.35} ${yBase - 36} ${progress * 0.7} ${yBase + 12} ${progress} ${yBase - 18}`}
            fill="none"
            stroke={`rgba(127,226,255,${0.14 + i * 0.05})`}
            strokeWidth={2}
          />
        );
      })}
      {new Array(26).fill(0).map((_, i) => {
        const x = (i * 79 + frame * 1.6) % 1920;
        const y = 140 + ((i * 43) % 800);
        const pulse = 3 + Math.sin((frame + i * 20) / 18) * 1.3;
        return <circle key={`p-${i}`} cx={x} cy={y} r={pulse} fill="rgba(120,248,255,0.65)" />;
      })}
    </svg>
  );
};

export const AICourseVideo: React.FC = () => {
  const frame = useCurrentFrame();
  const activeSubtitle = subtitleData.find((s) => frame >= s.start && frame < s.end) ?? null;
  useSpeechNarration(activeSubtitle?.text ?? null);

  return (
    <AbsoluteFill style={{backgroundColor: '#050b14'}}>
      <Sequence from={0} durationInFrames={300}>
        <SceneLayer src="/slides/1TitlePage.png" sceneFrame={frame} />
      </Sequence>
      <Sequence from={300} durationInFrames={330}>
        <SceneLayer src="/slides/2InNotNow.png" sceneFrame={frame - 300} />
      </Sequence>
      <Sequence from={630} durationInFrames={300}>
        <SceneLayer src="/slides/3intro.png" sceneFrame={frame - 630} />
      </Sequence>
      <Sequence from={930} durationInFrames={285}>
        <SceneLayer src="/slides/4Assignment.png" sceneFrame={frame - 930} />
      </Sequence>
      <Sequence from={1215} durationInFrames={105}>
        <SceneLayer src="/slides/5Thanks.png" sceneFrame={frame - 1215} />
      </Sequence>

      <DataViz />
      <FloatingSymbols />
      <HUDOverlay />

      <div
        style={{
          position: 'absolute',
          right: 42,
          top: 40,
          width: 470,
          height: 260,
          borderRadius: 18,
          background: 'rgba(6, 19, 34, 0.56)',
          border: '1px solid rgba(114,215,255,0.45)',
          boxShadow: '0 0 28px rgba(71,216,255,0.18)',
          padding: 22,
          overflow: 'hidden',
          fontFamily: 'JetBrains Mono, Menlo, monospace',
          color: '#9adfff',
          fontSize: 19,
          lineHeight: 1.4,
        }}
      >
        <div style={{opacity: 0.8, marginBottom: 8}}>AI_POLICY_ANALYZER.ts</div>
        <div style={{whiteSpace: 'pre'}}>
          {`const model = "gemini"\nawait ai.research(policySet)\nslides = ai.generateDeck(topic)\nwebapp.compile(assignments)`}
        </div>
      </div>

      <div
        style={{
          position: 'absolute',
          left: 54,
          bottom: 210,
          width: 420,
          height: 220,
          borderRadius: 22,
          background: 'rgba(7, 25, 45, 0.62)',
          border: '1px solid rgba(124,242,255,0.34)',
          padding: '18px 20px',
          color: '#d3f7ff',
          fontFamily: 'Inter, Arial, sans-serif',
          overflow: 'hidden',
        }}
      >
        <div style={{fontSize: 16, opacity: 0.7, marginBottom: 8}}>AI Classroom Chat</div>
        {new Array(4).fill(0).map((_, i) => (
          <div
            key={`chat-${i}`}
            style={{
              marginTop: 10,
              transform: `translateY(${((frame * 0.6 + i * 34) % 150) - 40}px)`,
              opacity: 0.3 + i * 0.15,
              fontSize: 18,
            }}
          >
            {i % 2 === 0 ? '→ Suggest policy comparison framework...' : '✓ Drafting collaborative rubric with AI...'}
          </div>
        ))}
      </div>

      <Subtitle />
    </AbsoluteFill>
  );
};
